name: Merge Android Kernel Change

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
    inputs:
      target_branch:
        description: 'Target branch to merge into'
        required: true
        default: 'main'
        type: string

jobs:
  merge-android-change:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.target_branch }}
        fetch-depth: 0  # Fetch all history for proper merging

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Fetch Android kernel change
      run: |
        git fetch https://android.googlesource.com/kernel/common refs/changes/63/3615663/3

    - name: Create and checkout temporary branch
      run: |
        git checkout -b change-3615663 FETCH_HEAD

    - name: Checkout target branch
      run: |
        git checkout ${{ github.event.inputs.target_branch }}

    - name: Attempt merge
      run: |
        # Try to merge, but don't fail immediately if there are conflicts
        if git merge --no-ff change-3615663 -m "Merge Android kernel change 3615663/3"; then
          echo "MERGE_SUCCESS=true" >> $GITHUB_ENV
        else
          echo "Merge failed, likely due to conflicts"
          echo "MERGE_SUCCESS=false" >> $GITHUB_ENV
          # Abort the merge to clean up
          git merge --abort || true
        fi

    - name: Push successful merge
      if: env.MERGE_SUCCESS == 'true'
      run: |
        git push origin ${{ github.event.inputs.target_branch }}

    - name: Create PR for conflicted merge
      if: env.MERGE_SUCCESS == 'false'
      run: |
        # Checkout the change branch again
        git checkout change-3615663
        # Push it to a feature branch
        git push origin change-3615663:android-change-3615663
        
        # Create a PR using GitHub CLI
        echo "Creating pull request for manual conflict resolution"
        gh pr create \
          --base "${{ github.event.inputs.target_branch }}" \
          --head "android-change-3615663" \
          --title "Merge Android kernel change 3615663/3 (NEEDS CONFLICT RESOLUTION)" \
          --body "This PR contains the Android kernel change that could not be automatically merged. Please resolve conflicts manually."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: |
        # Delete the local temporary branch
        git branch -D change-3615663 || true
