name: Merge Android Kernel Change 3653920/1

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
    inputs:
      target_branch:
        description: 'Target branch to merge into'
        required: true
        default: 'main'
        type: string

jobs:
  merge-android-change:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes
      pull-requests: write  # Needed to create PRs
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.target_branch }}
        fetch-depth: 0  # Fetch all history for proper merging

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Fetch Android kernel change 3653920/1
      run: |
        git fetch https://android.googlesource.com/kernel/common refs/changes/20/3653920/1

    - name: Create and checkout temporary branch
      run: |
        git checkout -b change-3653920 FETCH_HEAD

    - name: Checkout target branch
      run: |
        git checkout ${{ github.event.inputs.target_branch }}

    - name: Attempt merge
      run: |
        # Try to merge, but don't fail immediately if there are conflicts
        if git merge --no-commit --no-ff change-3653920; then
          git commit -m "Merge Android kernel change 3653920/1"
          echo "MERGE_SUCCESS=true" >> $GITHUB_ENV
        else
          echo "Merge failed, likely due to conflicts"
          echo "MERGE_SUCCESS=false" >> $GITHUB_ENV
          # Check if there are conflicts
          if git diff --check --diff-filter=U; then
            echo "CONFLICTS_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CONFLICTS_DETECTED=false" >> $GITHUB_ENV
          fi
        fi

    - name: Push successful merge
      if: env.MERGE_SUCCESS == 'true'
      run: |
        git push origin ${{ github.event.inputs.target_branch }}

    - name: Create PR for conflicted merge
      if: env.MERGE_SUCCESS == 'false' && env.CONFLICTS_DETECTED == 'true'
      run: |
        # Push the change branch to origin
        git checkout change-3653920
        git push -f origin change-3653920:android-change-3653920
        
        # Install GitHub CLI
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y
        
        # Create a PR using GitHub CLI
        gh pr create \
          --base "${{ github.event.inputs.target_branch }}" \
          --head "android-change-3653920" \
          --title "Merge Android kernel change 3653920/1 (NEEDS CONFLICT RESOLUTION)" \
          --body "This PR contains the Android kernel change that could not be automatically merged. Please resolve conflicts manually." \
          --label "merge-conflict"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Handle merge failure without conflicts
      if: env.MERGE_SUCCESS == 'false' && env.CONFLICTS_DETECTED == 'false'
      run: |
        echo "Merge failed for reasons other than conflicts. Check the logs for details."
        exit 1

    - name: Clean up
      run: |
        # Delete the local temporary branch
        git branch -D change-3653920 || true
